### browse with NWBwidget
- Uncomment !pip install nwbwidgets for nwbwidgets first time use 
- this code simply loads in the NWB and allows you to look through it
- simply provide the path to the NWB

In [2]:
# !pip install nwbwidgets

### load the nwb file

In [3]:
from pynwb import NWBHDF5IO
from nwbwidgets import nwb2widget
import dlab.psth_and_raster as psth

In [13]:
nwb_save_path = r'G:\Grant\neuropixels\nwb\reach7_07_2024-12-04_20-57-49_008____2025-02-03_14-16-34'
nwb_save_path = r"G:\Grant\neuropixels\nwb\Reach15"
io = NWBHDF5IO(nwb_save_path, mode='r')
nwb_ = io.read()

In [14]:
df_stim = nwb_.trials.to_dataframe()
# df_opto = nwb_.get_time_intervals('optogenetics_states').to_dataframe()
df_units = nwb_.units.to_dataframe()

In [15]:
df_stim.head()
df_stim

,start_time,stop_time,stimulus,optogenetics_LED_state
id,,,,
0,10239.422800,10239.422800,tone1_timestamps,0
1,10261.289967,10261.289967,tone1_timestamps,0
2,10283.329000,10283.329000,tone1_timestamps,0
3,10304.578900,10304.578900,tone1_timestamps,0
4,10382.254700,10382.254700,tone1_timestamps,0
...,...,...,...,...
1352819,18950.548600,18950.548600,opto_tagging_timestamps,0
1352820,18952.562467,18952.562467,opto_tagging_timestamps,0
1352821,18954.575767,18954.575767,opto_tagging_timestamps,0
1352822,18956.580033,18956.580033,opto_tagging_timestamps,0
1352823,18958.595000,18958.595000,opto_tagging_timestamps,0

In [16]:
df_units

,depth,xpos,ypos,label,KSlabel,KSamplitude,KScontamination,probe,bc_ROI,Brain_Region,bc_unitType,bc_classificationReason,spike_times
id,,,,,,,,,,,,,
0,3120.0,277.0,30.0,0,2,9.5,14.5,A,IN_ROI,SIM,NOISE,NOISE,"[10771.0, 11243.0, 11411.0, 12302.0, 38571.0, ..."
1,3120.0,277.0,30.0,0,2,10.3,17.2,A,IN_ROI,SIM,NOISE,NOISE,"[8863.0, 10208.0, 10610.0, 10822.0, 11005.0, 1..."
2,3120.0,59.0,30.0,0,1,9.0,0.0,A,IN_ROI,SIM,NOISE,NOISE,"[2016.0, 36055.0, 81992.0, 92957.0, 122673.0, ..."
3,2775.0,27.0,375.0,0,2,8.5,0.0,A,IN_ROI,SIM,NOISE,NOISE,"[24865.0, 69387.0, 89250.0, 278684.0, 284726.0..."
4,2745.0,59.0,405.0,0,2,9.1,7.4,A,IN_ROI,SIM,NOISE,NOISE,"[6779.0, 13517.0, 16230.0, 18967.0, 23039.0, 2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,860.0,43.0,3740.0,0,1,10.2,175.3,F,IN_ROI,RN,NON-SOMA,NON-SOMA,"[45015.0, 45814.0, 49002.0, 104794.0, 168633.0..."
4596,1020.0,43.0,3580.0,0,2,19.5,0.0,F,IN_ROI,RN,NOISE,NOISE,"[29445397.0, 29445847.0, 29447197.0, 31932627...."
4597,1060.0,11.0,3540.0,0,1,9.6,236.7,F,IN_ROI,RN,NOISE,NOISE,"[1761108.0, 3349020.0, 3370127.0, 4288389.0, 4..."
4598,980.0,43.0,3620.0,0,2,26.1,0.0,F,IN_ROI,RN,NON-SOMA,NON-SOMA,"[29445096.0, 29445546.0, 29445996.0, 29446446...."
4599,980.0,43.0,3620.0,0,1,10.6,202.1,F,IN_ROI,RN,NON-SOMA,NON-SOMA,"[192155.0, 250956.0, 582053.0, 602337.0, 60347..."

In [17]:
nwb2widget(nwb_)

VBox(children=(HBox(children=(Label(value='session_description:', layout=Layout(max_height='40px', max_width='…

### Verify the df_units contents

In [3]:
import os 
import pathlib as path
import glob
import pandas as pd


df_units_json_path = r"H:\Grant\Neuropixels\Kilosort_Recordings\Reach15_20260201_session007_NP_Recording_Number02_2026-02-01_18-25-00\Record Node 103\experiment1\recording1\continuous\intermediates\df_units.json"

df_units_json = pd.read_json(df_units_json_path)
df_units_json

,cluster_id,Amplitude,ContamPct,KSLabel,amp,ch,depth,fr,group,n_spikes,sh,probe,times,amplitudes,template,peak_wv,xpos,ypos
0,0,9.5,14.5,good,533.356750,52,3120,1.568448,noise,14579,2,A,"[10771, 11243, 11411, 12302, 38571, 38778, 394...","[14.236158371, 19.1880664825, 14.9268636703, 1...","[[-0.4574440122, 0.0, 0.0, 0.0, 0.0, -0.389908...","[-0.2724888623, -0.2905825675, -0.3499784768, ...",277,30
1,1,10.3,17.2,good,571.813965,52,3120,3.815850,noise,35469,2,A,"[8863, 10208, 10610, 10822, 11005, 11678, 1182...","[14.9170703888, 16.1354160309, 15.6884231567, ...","[[0.5283487439, 0.0, 0.0, 0.0, 0.0, 0.38021734...","[0.2653385699, 0.2762833834, 0.3342554271, 0.3...",277,30
2,2,9.0,0.0,mua,519.271912,5,3120,0.018935,noise,176,1,A,"[2016, 36055, 81992, 92957, 122673, 124905, 12...","[11.5004234314, 14.7121496201, 14.3968000412, ...","[[-0.0978831351, 0.0, 0.0, 0.0, 0.0, -0.440404...","[-0.4404040575, -0.4415953755, -0.5235797763, ...",59,30
3,3,8.5,0.0,good,1199.464355,98,2775,0.041527,None,386,1,A,"[24865, 69387, 89250, 278684, 284726, 328430, ...","[11.5197925568, 14.3008356094, 12.1395072937, ...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.1844317019, 0.17824926970000002, 0.21420317...",27,375
4,4,9.1,7.4,good,974.952637,103,2745,1.093470,None,10164,1,A,"[6779, 13517, 16230, 18967, 23039, 26460, 2666...","[14.0649929047, 13.3076658249, 11.9300498962, ...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.19008165600000002, 0.1629859507, 0.19040936...",59,405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,686,10.2,175.3,mua,415.928284,371,860,1.555861,None,14462,0,F,"[45015, 45814, 49002, 104794, 168633, 190767, ...","[10.763183593800001, 11.2275819778, 12.2610006...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[-0.1550015062, -0.1638487726, -0.2120242119, ...",43,3740
4596,687,19.5,0.0,good,1056.609497,355,1020,0.020118,None,187,0,F,"[29445397, 29445847, 29447197, 31932627, 31933...","[22.0562610626, 23.1712779999, 23.4062919617, ...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",43,3580
4597,688,9.6,236.7,mua,369.616760,352,1060,0.202148,None,1879,0,F,"[1761108, 3349020, 3370127, 4288389, 4629859, ...","[14.0271472931, 12.3372888565, 14.2292566299, ...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",11,3540
4598,689,26.1,0.0,good,2964.238281,359,980,0.102096,None,949,0,F,"[29445096, 29445546, 29445996, 29446446, 29446...","[32.3722000122, 32.6644325256, 32.7623634338, ...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",43,3620
4599,690,10.6,202.1,mua,783.736450,359,980,1.374476,None,12776,0,F,"[192155, 250956, 582053, 602337, 603471, 82979...","[12.5631074905, 10.1025972366, 12.0907115936, ...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",43,3620

In [10]:
# extract times from df_units_json per probe and KSlabel
df1 = df_units_json[df_units_json.probe == 'A'][df_units_json.KSLabel == 'good']
df1[0:5]
unit_idx = 1
spike_times = df1.times.values[unit_idx]  
spike_times[0:10]
spike_times[-5:]

C:\Users\user\AppData\Local\Temp\ipykernel_8\4152912576.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1 = df_units_json[df_units_json.probe == 'A'][df_units_json.KSLabel == 'good']

[278768743, 278795556, 278851596, 278852699, 278854569]